version: '3'
services:
  tram-cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M10
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuate/cdc/leader/eventuatetram
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 2
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_NAME: ClientEventuateTram
      EVENTUATELOCAL_CDC_OFFSET_STORAGE_TOPIC_NAME: db.history.eventuate.tram
  eventuate-local-cdc-service:
    image: eventuateio/eventuateio-local-cdc-service:0.30.0.M14
    ports:
      - "8098:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
      EVENTUATELOCAL_CDC_LEADERSHIP_LOCK_PATH: /eventuate/cdc/leader/eventuatelocal
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_NAME: ClientEventuateLocal
      EVENTUATELOCAL_CDC_OFFSET_STORAGE_TOPIC_NAME: db.history.eventuate.local
